server:
  port: 9091
spring:
  application:
    name: user-server
  cloud:
      config:                                 #配置中心获取配置文件
        enabled: true
        uri: http://localhost:8889
        failFast: true
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://wugf:123456@localhost:8761/eureka

#配置不启用安全策略才能使用 spring cloud 端点
management:
  security:
    enabled: false
