spring:
  application:
    name: git-config-server
  #消息总线配置
  cloud:
    bus:
      trace:
        enabled: true
#加密对称配置
encrypt:
  key: foo
#配置不启用安全策略才能使用 actuator 端点
management:
  security:
    enabled: false

---
server:
  port: 8900
spring:
  profiles: local
  rabbitmq:
    host: 39.108.107.103
    port: 8083
    username: guest
    password: guest
  #github仓库配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/z515535/config.git
          searchPaths: config-local
eureka:
  client:
    serviceUrl:
      defaultZone: http://wugf:123456@localhost:8761/eureka


---
server:
  port: 8901
spring:
  profiles: dev
  #github仓库配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/z515535/config.git
          searchPaths: config-dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://wugf:123456@localhost:8761/eureka
---