#负载均衡配置
order-server:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#hystrix 查看监控端点 hystrix.stream支持的最大并发
hystrix:
  config:
    stream:
      maxConcurrentConnections: 10

#启用重试机制
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
  ribbon:
   # 同一实例最大重试次数，不包括首次调用
    MaxAutoRetries: 1
    # 重试其他实例的最大重试次数，不包括首次所选的server
    MaxAutoRetriesNextServer: 2
   # 是否所有操作都进行重试
    OkToRetryOnAllOperations: false