server:
  port: 8761

eureka:
  client:
    #是否将自己注册到 eureka服务中
    registerWithEureka: false
    #是否获取eureka服务的注册信息，eureka集群才使用
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka